"""1

Revision ID: fe4e775afa5b
Revises: d21b9b27d766
Create Date: 2021-09-04 14:52:30.850043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe4e775afa5b'
down_revision = 'd21b9b27d766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
